service: toggl-sync-timesheet-v2

provider: 
  memorySize: 512
  name: aws
  runtime: nodejs8.10
  versionFunctions: true

plugins: 
  - serverless-dotenv-plugin

functions: 
  toggl_sync: 
    handler: handler.toggl
    events: 
      - 
        schedule: 
          enabled: true
          rate: cron(0 0 * * ? *)