service: toggl-sync-timesheet-v2

provider: 
  memorySize: 256
  name: aws
  runtime: nodejs8.10
  versionFunctions: true

plugins: 
  - serverless-dotenv-plugin

functions: 
  toggl_sync: 
    handler: 'handler.sync'
    events: 
      - 
        schedule: 
          enabled: true
          rate: cron(0 0 * * ? *)
    
  toggl_refresh:
    handler: 'handler.refresh'
    events: 
      - 
        schedule: 
          enabled: true
          rate: cron(0/15 9-18 ? * MON-FRI *)
